version: '3.7' #指定版本
services:    #服务根节点
  redis:     #redis服务/其他服务（web服务/nginx服务等）
      image: redis:7                            #redis镜像，如果镜像容器没有会去自动拉取
      container_name: redis                     #设置容器名称
      command: redis-server --appendonly yes --requirepass '123456'    #开启持久化的支持并设置认证密码
      restart: always                           #跟随docker的启动而启动
      volumes:
        - ./mydata/redis/data:/data              #数据文件挂载
      ports:
        - 6379:6379

  mariadb:
    image: mariadb:10.5.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234567"
      TZ: "Asia/Shanghai"
    ports:
      - "3306:3306"
    volumes:
      - ./mydata/mariadb:/var/lib/mysql
      - ./mydata/mariadb/log:/var/log/mysql
      - ./mydata/mariadb/conf/my.cnf:/etc/mysql/conf.d

  rabbit:
    image: rabbitmq:3.8-management
    hostname: rabbit
    container_name: "rabbitmq"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123123
    volumes:
      - ./mydata/rabbitmq/data:/var/lib/rabbitmq

  lgtm:
    image: grafana/otel-lgtm
    ports:
      - '4317:4317'
      - '4318:4318'
      - '3000:3000'